permalink: /:year/:month/:title/
url: "https://jonduan.github.io/write"
baseurl: "/write"
author: jd
highlighter: rouge
timezone: Asia/Shanghai
gems: [jekyll-paginate]
paginate: 24
markdown: kramdown
#auto: true
encoding: "utf-8"
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
#  syntax_highlighter_opts:: {disable: true}
